### Default variable file for taxonomy-service ###

api_namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: docker.io/sanketikahub/taxonomy-service
image_tag: R5.7.0
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 9006
  targetport: 9000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%
serviceType: LoadBalancer 
#cassandra_connection: cassandra-db.knowlg-db.svc.cluster.local:9042
cassandra_connection: cassandra.knowlg-db.svc.cluster.local:9042
redis_connection: redis-master.knowlg-db.svc.cluster.local
neo4j_domain_connection: neo4j.knowlg-db.svc.cluster.local:7687
neo4j_all_connection: neo4j.knowlg-db.svc.cluster.local:8687  
kafka_connection: kafka-headless.knowlg-db.svc.cluster.local:9092
objectcategorydefinition_keyspace: dev_category_store
schema_base_path: ${schema_base_path}