api_namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: docker.io/aimansharief/dial-service
image_tag: TR6.0.1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 9000
  targetport: 9000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%
serviceType: LoadBalancer
cassandra_connection: cassandra.knowlg-db.svc.cluster.local:9042
redis_connection: redis-master.knowlg-db.svc.cluster.local
es_connection: elasticsearch.knowlg-db.svc.cluster.local:9200
kafka_connection: kafka-headless.knowlg-db.svc.cluster.local:9092
dialcode_keyspace_name: dev_dialcode_store
dialcode_keyspace_table: dial_code
systemconfig_keyspace_name: dev_dialcode_store
systemconfig_table: system_config
publisher_keyspace_name: dev_dialcode_store
publisher_keyspace_table: publisher
qrcodes_keyspace_name: dialcodes
qrcodes_keyspace_table: dialcode_batch
dialcode_object_type: DialCode
graph_event: dev.knowlg.learning.graph.events
dial_request_topic: dev.knowlg.qrimage.request
dialocode_object_type: DialCode
dial_storage_container: dial
