### Default variable file for search-service ###

api_namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: docker.io/sanketikahub/knowlg-search
image_tag: R5.7.0
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 9006
  targetport: 9000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%
serviceType: LoadBalancer
es_connection: elasticsearch.knowlg-db.svc.cluster.local:9200
schema_base_path: ${schema_base_path}

